In [1]:
import torch
import numpy as np
from numpy import sin,cos

定义训练集

In [2]:
train_x=[]
train_y=[]
for x1 in np.linspace(-1,1,100):
    for x2 in np.linspace(-1,1,100):
        train_x.append([x1,x2])
        train_y.append([sin(x1)**3+cos(x2)])
train_x=torch.Tensor(train_x)
train_y=torch.Tensor(train_y)


In [16]:
print(train_x.shape)
train_x[0]

torch.Size([10000, 2])


tensor([-1., -1.])

In [17]:
print(train_y.shape)
train_y[0]

torch.Size([10000, 1])


tensor([-0.0555])

定义网络

In [18]:
class Net(torch.nn.Module):
    def __init__(self,input_dim):
        super(Net,self).__init__()
        self.w1=torch.nn.Linear(input_dim,64)
        self.w2=torch.nn.Linear(64,1)
    def forward(self,x):
        x=torch.relu(self.w1(x))
        return self.w2(x)

建立网络，定义优化器和损失函数

In [22]:
net=Net(2)
print(net)
opt=torch.optim.Adam(net.parameters())
print(opt)
MSE=torch.nn.MSELoss()
MSE

Net(
  (w1): Linear(in_features=2, out_features=64, bias=True)
  (w2): Linear(in_features=64, out_features=1, bias=True)
)
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0
)


MSELoss()

In [23]:
for i in range(100):
    out=net(train_x)
    loss=MSE(out,train_y)
    opt.zero_grad()
    loss.backward()
    opt.step()

print(out)
print(loss)

tensor([[0.2908],
        [0.2956],
        [0.2997],
        ...,
        [1.2934],
        [1.2971],
        [1.3005]], grad_fn=<AddmmBackward>)
tensor(0.0314, grad_fn=<MseLossBackward>)


In [25]:
net.eval()
error=MSE(net(train_x),train_y)
print(net(train_x))
print(train_y)
error

tensor([[0.2860],
        [0.2907],
        [0.2948],
        ...,
        [1.2970],
        [1.3007],
        [1.3041]], grad_fn=<AddmmBackward>)
tensor([[-0.0555],
        [-0.0386],
        [-0.0220],
        ...,
        [ 1.1697],
        [ 1.1530],
        [ 1.1361]])


tensor(0.0310, grad_fn=<MseLossBackward>)

In [13]:
res=Net(2)
opt=torch.optim.Adam(res.parameters())
for i in range(100):
    out=res(train_x)
    print(out)
    # 残差
    loss=MSE(out,train_y-net(train_x))
    opt.zero_grad()
    loss.backward()
    opt.step()

torch.Size([10000, 1])


In [8]:
res.eval()
res_error=MSE(net(train_x)+res(train_x),train_y)
res_error

tensor(0.0107, grad_fn=<MseLossBackward>)

In [9]:
pred=net(train_x)+res(train_x)
pred

tensor([[0.2009],
        [0.2077],
        [0.2144],
        ...,
        [1.1979],
        [1.1904],
        [1.1821]], grad_fn=<AddBackward0>)

In [10]:
train_y

tensor([[-0.0555],
        [-0.0386],
        [-0.0220],
        ...,
        [ 1.1697],
        [ 1.1530],
        [ 1.1361]])