In [1]:
import sys, os
from pathlib import Path

path = Path(os.getcwd())
sys.path.append(str(path.parent))

import BayesKeras
from BayesKeras import PosteriorModel
from BayesKeras import analyzers

import tensorflow as tf
from tensorflow.keras.models import *
from tensorflow.keras.layers import *

import numpy as np

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
X_train = X_train / 255.
X_test = X_test / 255.
X_train = X_train.astype("float32").reshape(-1, 28 * 28)
X_test = X_test.astype("float32").reshape(-1, 28 * 28)



D:\Users\T470\Anaconda3\envs\CertifiableBayesianInference\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
inference = "BBB"
rob = 2
num_images = 500

In [4]:
model = PosteriorModel("%s_FCN_Posterior_%s_mine" % (inference, rob))

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, None, None, 512)   401920    
                                                                 
 dense_9 (Dense)             (None, None, None, 10)    5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________
BayesKeras detected the above model 


==========================posterior_mean_start==========================
[<tf.Tensor: shape=(784, 512), dtype=float32, numpy=
 array([[-0.00117524, -0.00130718, -0.00062442, ..., -0.00214078,
         -0.00109595,  0.00662703],
        [-0.00140605, -0.00124328, -0.00113443, ..., -0.00153678,
         -0.00130616,  0.00883936],
        [-0.0017624 , -0.00128564, -0.00082267, ..., -0.00111104,
         

In [5]:
epistemic, aleatoric = analyzers.variational_uncertainty(model, X_test[0:num_images])

Pred shape:  (35, 500, 10)


In [6]:
epistemic[0]

array([7.8796582e-38, 6.0080056e-25, 5.5795515e-28, 1.4628986e-29,
       1.4012985e-45, 7.3537605e-37, 0.0000000e+00, 0.0000000e+00,
       3.8844694e-40, 3.8252911e-35], dtype=float32)

In [7]:
aleatoric[0]

array([4.8157214e-20, 1.6769176e-13, 4.1534066e-15, 7.3478224e-16,
       8.6865442e-24, 2.9912441e-19, 3.1848062e-27, 0.0000000e+00,
       5.9843343e-21, 1.1063117e-18], dtype=float32)

In [8]:
auc = analyzers.auroc(model, X_test[0:num_images], y_test[0:num_images])

print("ON MNIST")
print("-------------------------------")
print("Epistemic: ", np.mean(epistemic))
print("Aleatoric: ", np.mean(aleatoric))
print("AUC: ", auc)
print("-------------------------------")

ON MNIST
-------------------------------
Epistemic:  0.0019399946
Aleatoric:  0.0017630946
AUC:  0.9985302316718541
-------------------------------
